# Generated by Django 5.2.4 on 2025-07-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_reader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='author',
        ),
        migrations.RemoveField(
            model_name='reader',
            name='ebook',
        ),
        migrations.RemoveField(
            model_name='reader',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='reader',
            name='year',
        ),
        migrations.AddField(
            model_name='book',
            name='ebook',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='filename',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.IntegerField(default=2025),
            preserve_default=False,
        ),
    ]
